### ISSUE TITLE
希望能增加玩家自我簡介功能

### ISSUE THREAD

**Issue by TheDark0825** [ACGN-stock/acgn-stock#212]
希望能在玩家的帳號列表中開出一個欄位
能夠讓玩家填寫簡單的自我簡介
可以的話希望像是填寫公司角色簡介一般的界面
這樣的話需要在玩家帳號頁面內多出一個可縮放的欄位

或是採取比較簡單的形式
類似股東會留言的輸入方式與字數限制
輸入資訊後會像是擔任經理或員工資訊顯示在玩家帳號資訊的下方

不知道這樣的功能能不能新增呢？

**Comment by erase2004** [comment]
Let me pick it up.

**Comment by SoftwareSing** [comment]
#645
