### ISSUE TITLE
不知道為什麼本週未收到任何分紅？G:ywang146@ncsu.edu

### ISSUE THREAD

**Issue by ywang146** [ACGN-stock/acgn-stock#668]

**Comment by lamlam77777** [comment]
(2022/06/05 23:29:55) ⟨G帳⟩ywang146@ncsu.edu從27.184.24.185登入了系統！
(2022/05/31 16:17:01) ⟨G帳⟩ywang146@ncsu.edu從218.188.148.71登入了系統！
(2022/05/31 12:38:06) ⟨G帳⟩ywang146@ncsu.edu從2408:821a:421:5ff0:ad52:fe33:e147:375f登入了系統！
(2022/05/28 14:19:46) ⟨G帳⟩ywang146@ncsu.edu從218.188.148.71登入了系統！
(2022/05/28 11:28:41) ⟨G帳⟩ywang146@ncsu.edu從60.1.125.114登入了系統！
不上線還想拿分紅
