### ISSUE TITLE
[BUG回報]未發放分紅 G:ywang146

### ISSUE THREAD

**Issue by ywang146** [ACGN-stock/acgn-stock#669]

**Comment by speedypard** [comment]
若未登入天數達到五天以上，則持股數以 0% 計。（換句話說就是拿不到分紅！）
上一封已經告知過了，麻煩請去看說明
https://hackmd.io/@ACGN-stock/manual/https%3A%2F%2Fhackmd.io%2F%40ACGN-stock%2Fcompany
